# Generated by Django 3.2.4 on 2021-07-03 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backstellar',
            name='nich',
            field=models.CharField(blank=None, default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backstellar',
            name='wacktu',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
