# Generated by Django 3.2.4 on 2021-07-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slur', '0002_auto_20210703_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backstellar',
            name='nich',
            field=models.CharField(blank=None, max_length=40),
        ),
    ]
