# Generated by Django 3.2.4 on 2021-07-05 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slur', '0003_alter_backstellar_nich'),
    ]

    operations = [
        migrations.AddField(
            model_name='backstellar',
            name='pitjture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='bglur'),
            preserve_default=False,
        ),
    ]
